#pragma once

namespace brogueHd::backend::modelConstant
{
	enum statusEffects
	{
		STATUS_SEARCHING = 0,
		STATUS_DONNING,
		STATUS_WEAKENED,
		STATUS_TELEPATHIC,
		STATUS_HALLUCINATING,
		STATUS_LEVITATING,
		STATUS_SLOWED,
		STATUS_HASTED,
		STATUS_CONFUSED,
		STATUS_BURNING,
		STATUS_PARALYZED,
		STATUS_POISONED,
		STATUS_STUCK,
		STATUS_NAUSEOUS,
		STATUS_DISCORDANT,
		STATUS_IMMUNE_TO_FIRE,
		STATUS_EXPLOSION_IMMUNITY,
		STATUS_NUTRITION,
		STATUS_ENTERS_LEVEL_IN,
		STATUS_MAGICAL_FEAR,
		STATUS_ENTRANCED,
		STATUS_DARKNESS,
		STATUS_LIFESPAN_REMAINING,
		STATUS_SHIELDED,
		STATUS_INVISIBLE,
		STATUS_AGGRAVATING,
		NUMBER_OF_STATUS_EFFECTS
	};
}